### PR TITLE
adding slack notification template for monit

### PR DESCRIPTION
**Pull request by RahulMahale**

### CODE REVIEW

**Comment by ershad** [comment]
@RahulMahale _a please take care of the following.

1) Update a new/existing node file with slack webhook as an example.
2) Squash the commits to 1 commit.
3) What should we change to enable slack webhook for a specific monit config (Eg: delayed job monit config)?

**Comment by RahulMahale** [comment]
@ershad _a
Here is the node file to use monit slack alert https://gist.github.com/RahulMahale/bfb9cc5fc282fb22ced5febf1ceb7f8c

To use slack alerts in nginx config added a condition in nginx monit template  ```templates/default/monit/nginx.conf.erb```

**Comment by ershad** [comment]
@RahulMahale _a looks good now. I think the major use case of this slack notification is to know when unicorn/dj goes down and doesn't restart automatically, or if it takes more than usual time to come up. Can you please configure notifications for those too?

**Comment by RahulMahale** [comment]
@ershad have pushed PR for delayed job and unicorn to use slack alerts when processes are down do check https://github.com/bigbinary/boxy-delayed-job/pull/1  and https://github.com/bigbinary/boxy-unicorn/pull/2

**Pull request merged**
